{{- $root := . -}}
{{- range $role := list "dependencies" "api" "worker" }}
{{- $context := dict "root" $root "role" $role }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inference-platform.roleName" $context }}
  labels:
    {{- include "inference-platform.labels" $context | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
